### ISSUE TITLE
ArgumentCountError: Too few arguments to function OTPHP\OTP::getQrCodeUri() in \vendor\vxm\yii2-mfa\src\Otp.php on line 107 and exactly 2 expected

### ISSUE THREAD

**Issue by xandros15** [vuongxuongminh/yii2-mfa#3]
When trying to generate QR code I will get that error.
The problem is the Spomky-Labs/OTP in v10 doesn't support default second parametr:

https://github.com/Spomky-Labs/otphp/commit/903e1b926fac2b33c4d5d0e7dc79dd6d19b2ded1#diff-2b8d9d05a6b332d185e48a0e82889b14R30

The easier fix is just force require ^9.0 in composer.json instead of *.

**Comment by vuongxuongminh** [comment]
Thank you. Feel free to open PR.

**Comment by vuongxuongminh** [comment]
Solved, thank you!
